### ISSUE TITLE
items are not sucked into the hopper in pocketmine 4.12.0

### ISSUE THREAD

**Issue by BeeAZ-pm-pl** [ColinHDev/VanillaHopper#2]

**Comment by BeeAZ-pm-pl** [comment]
<img width="480" alt="d" src="https://user-images.githubusercontent.com/89953941/205496975-15162788-0d9e-4fda-a262-f88f03cd66b3.png">

**Comment by ColinHDev** [comment]
Ah, I completely forgot that there were some changes planned to the entity events. This should be a simple fix

**Comment by BeeAZ-pm-pl** [comment]
Can you fix it soon? Please

**Comment by ColinHDev** [comment]
This was fixed in
- commit: 129178694a0b875d56d6718523c768b36be01d72
- release: https://github.com/ColinHDev/VanillaHopper/releases/tag/v2.1.0
